/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danda
 */
public class EdiçãoAlunos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EdiçãoAlunos.class.getName());
    private int idAluno;

    /**
     * Creates new form TelaDificuldade
     */
    public EdiçãoAlunos(int idAluno) {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.idAluno = idAluno;
        carregarDadosAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        botãoFecharTotal = new javax.swing.JButton();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nomePágina = new javax.swing.JLabel();
        nomeEmail = new javax.swing.JLabel();
        colocarEmail = new javax.swing.JTextField();
        nomeUsuário = new javax.swing.JLabel();
        colocarUsuário = new javax.swing.JTextField();
        colocarSenha = new javax.swing.JTextField();
        nomeSenha = new javax.swing.JLabel();
        botãoAtualizar = new javax.swing.JButton();
        botãoVoltar = new javax.swing.JButton();
        botãoExcluir = new javax.swing.JButton();
        botãoSom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));
        cinzaPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(255, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        botãoFecharTotal.setText("X");
        botãoFecharTotal.addActionListener(this::botãoFecharTotalActionPerformed);

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botãoFecharTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botãoFecharTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(220, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomePágina.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomePágina.setText("Edição de Alunos");

        nomeEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeEmail.setText("Email Institucional");

        colocarEmail.addActionListener(this::colocarEmailActionPerformed);

        nomeUsuário.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeUsuário.setText("Usuário");

        colocarUsuário.addActionListener(this::colocarUsuárioActionPerformed);

        colocarSenha.addActionListener(this::colocarSenhaActionPerformed);

        nomeSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeSenha.setText("Senha");

        botãoAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoAtualizar.setText("Atualizar");
        botãoAtualizar.addActionListener(this::botãoAtualizarActionPerformed);

        botãoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoVoltar.setText("Voltar");
        botãoVoltar.addActionListener(this::botãoVoltarActionPerformed);

        botãoExcluir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoExcluir.setText("Excluir");
        botãoExcluir.addActionListener(this::botãoExcluirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(botãoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botãoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botãoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomeEmail)
                                .addComponent(nomeUsuário)
                                .addComponent(colocarEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                .addComponent(colocarUsuário)
                                .addComponent(nomeSenha)
                                .addComponent(colocarSenha))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(nomePágina)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nomePágina)
                .addGap(38, 38, 38)
                .addComponent(nomeEmail)
                .addGap(18, 18, 18)
                .addComponent(colocarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(nomeUsuário)
                .addGap(18, 18, 18)
                .addComponent(colocarUsuário, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(nomeSenha)
                .addGap(18, 18, 18)
                .addComponent(colocarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botãoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botãoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botãoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        botãoSom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoSom.setText("Som");
        botãoSom.addActionListener(this::botãoSomActionPerformed);

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(379, 379, 379))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                        .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addComponent(vermelhoPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colocarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colocarEmailActionPerformed

    private void colocarUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocarUsuárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colocarUsuárioActionPerformed

    private void botãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoVoltarActionPerformed
        // TODO add your handling code here:
        TelaEscolhaAlunos tela = new TelaEscolhaAlunos();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoVoltarActionPerformed

    private void colocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colocarSenhaActionPerformed

    private void botãoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoAtualizarActionPerformed
        // TODO add your handling code here:
        String email = colocarEmail.getText().trim();
        String nome = colocarUsuário.getText().trim();
        String senha = colocarSenha.getText().trim();
        
        if(nome.isEmpty() || email.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha usuário e senha");
            return;
        }
        
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco.");
                return;
            }
            
            PreparedStatement ps;
            
            if(senha.isEmpty()){
                String sql = "UPDATE usuarios SET nome = ?, email = ? WHERE id_usuario = ? AND tipo_usuario = 'Aluno'"; 
                ps = conexao.prepareStatement(sql);
                ps.setString(1, nome);
                ps.setString(2,email);
                ps.setInt(3, idAluno);
            }else{
                String senhaHash = SegurancaSenha.gerarHash(senha);
                String sql = "UPDATE usuarios SET nome = ?, email = ?, senha_hash = ? WHERE id_usuario = ? AND tipo_usuario = 'Aluno'";
                ps = conexao.prepareStatement(sql);
                ps.setString(1,nome);
                ps.setString(2,email);
                ps.setString(3,senhaHash);
                ps.setInt(4,idAluno);  
            }
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Aluno atualizado com sucesso!");
            
            conexao.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao atualizar aluno: " + e.getMessage());
        }
    }//GEN-LAST:event_botãoAtualizarActionPerformed

    private void botãoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoExcluirActionPerformed
        // TODO add your handling code here:

    int opcao = JOptionPane.showConfirmDialog(
            this,
            "Deseja excluir o aluno e todo o histórico de partidas?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (opcao == JOptionPane.YES_OPTION) {
        excluirAluno();
    }
    }//GEN-LAST:event_botãoExcluirActionPerformed

    private void botãoSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSomActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_botãoSomActionPerformed

    private void botãoFecharTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoFecharTotalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botãoFecharTotalActionPerformed
    private void carregarDadosAlunos(){
        try {
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco.");
                return;
            }
            
            String sql = "SELECT nome, email FROM usuarios WHERE id_usuario = ? and tipo_usuario = 'Aluno'";
            
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setInt(1, idAluno);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                colocarEmail.setText(rs.getString("email"));
                colocarUsuário.setText(rs.getString("nome"));
                colocarSenha.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Aluno não encontrado.");
            }
            conexao.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar aluno: " + e.getMessage());

        }
    }
    
    private void excluirAluno() {

    Connection conexao = null;

    try {
        ConnectionFactory c = new ConnectionFactory();
        conexao = c.obtemConexao();

        conexao.setAutoCommit(false);

        String sqlRespostas = """
            DELETE rp
            FROM respostas_partida rp
            INNER JOIN partidas p
                ON rp.id_partida = p.id_partida
            WHERE p.id_aluno = ?
        """;

        PreparedStatement psRespostas =
                conexao.prepareStatement(sqlRespostas);

        psRespostas.setInt(1, idAluno);
        psRespostas.executeUpdate();


        String sqlPartidas =
                "DELETE FROM partidas WHERE id_aluno = ?";

        PreparedStatement psPartidas =
                conexao.prepareStatement(sqlPartidas);

        psPartidas.setInt(1, idAluno);
        psPartidas.executeUpdate();


        String sqlUsuario =
                "DELETE FROM usuarios WHERE id_usuario = ?";

        PreparedStatement psUsuario =
                conexao.prepareStatement(sqlUsuario);

        psUsuario.setInt(1, idAluno);
        psUsuario.executeUpdate();


        conexao.commit();

        JOptionPane.showMessageDialog(
                this,
                "Aluno excluído com sucesso."
        );

    } catch (Exception e) {

        try {
            if (conexao != null) {
                conexao.rollback();
            }
        } catch (Exception erroRollback) {
            erroRollback.printStackTrace();
        }

        JOptionPane.showMessageDialog(
                this,
                "Erro ao excluir aluno: " + e.getMessage()
        );

    } finally {

        try {
            if (conexao != null) {
                conexao.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EdiçãoAlunos(2).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãoAtualizar;
    private javax.swing.JButton botãoExcluir;
    private javax.swing.JButton botãoFecharTotal;
    private javax.swing.JButton botãoSom;
    private javax.swing.JButton botãoVoltar;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JTextField colocarEmail;
    private javax.swing.JTextField colocarSenha;
    private javax.swing.JTextField colocarUsuário;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeEmail;
    private javax.swing.JLabel nomePágina;
    private javax.swing.JLabel nomeSenha;
    private javax.swing.JLabel nomeUsuário;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
