package com.mycompany.pi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import com.mycompany.pi.TelaDificuldade;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 26.00040-6
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    int numTela = 0; 

    /**
     * Creates new form telaLogin
     */
    public TelaLogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cinzaPane = new javax.swing.JPanel();
        mauaVermelhoPane = new javax.swing.JPanel();
        mauaCinzaPane = new javax.swing.JPanel();
        mauaLabel = new javax.swing.JLabel();
        etecVermelhoPane = new javax.swing.JPanel();
        etecCinzaPane = new javax.swing.JPanel();
        etecLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        entrarButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        mostrarSenhaBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));

        mauaVermelhoPane.setBackground(new java.awt.Color(148, 22, 17));

        mauaCinzaPane.setBackground(new java.awt.Color(74, 85, 92));
        mauaCinzaPane.setVerifyInputWhenFocusTarget(false);

        mauaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MAUA.png"))); // NOI18N

        javax.swing.GroupLayout mauaCinzaPaneLayout = new javax.swing.GroupLayout(mauaCinzaPane);
        mauaCinzaPane.setLayout(mauaCinzaPaneLayout);
        mauaCinzaPaneLayout.setHorizontalGroup(
            mauaCinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mauaCinzaPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mauaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        mauaCinzaPaneLayout.setVerticalGroup(
            mauaCinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mauaCinzaPaneLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(mauaLabel)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mauaVermelhoPaneLayout = new javax.swing.GroupLayout(mauaVermelhoPane);
        mauaVermelhoPane.setLayout(mauaVermelhoPaneLayout);
        mauaVermelhoPaneLayout.setHorizontalGroup(
            mauaVermelhoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mauaCinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mauaVermelhoPaneLayout.setVerticalGroup(
            mauaVermelhoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mauaVermelhoPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mauaCinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        etecVermelhoPane.setBackground(new java.awt.Color(148, 22, 17));

        etecCinzaPane.setBackground(new java.awt.Color(74, 85, 92));

        etecLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/etec_ra_metropolitana_sp_santo_andre_etec_julio_de_mesquita_cor (1).png"))); // NOI18N
        etecLabel.setText("jLabel3");

        javax.swing.GroupLayout etecCinzaPaneLayout = new javax.swing.GroupLayout(etecCinzaPane);
        etecCinzaPane.setLayout(etecCinzaPaneLayout);
        etecCinzaPaneLayout.setHorizontalGroup(
            etecCinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etecCinzaPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(etecLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        etecCinzaPaneLayout.setVerticalGroup(
            etecCinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etecCinzaPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(etecLabel)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout etecVermelhoPaneLayout = new javax.swing.GroupLayout(etecVermelhoPane);
        etecVermelhoPane.setLayout(etecVermelhoPaneLayout);
        etecVermelhoPaneLayout.setHorizontalGroup(
            etecVermelhoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etecCinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        etecVermelhoPaneLayout.setVerticalGroup(
            etecVermelhoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, etecVermelhoPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etecCinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        emailField.addActionListener(this::emailFieldActionPerformed);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailLabel.setText("Email Institucional");

        senhaLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        senhaLabel.setText("Senha");

        entrarButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        entrarButton.setText("Entrar");
        entrarButton.addActionListener(this::entrarButtonActionPerformed);

        senhaPasswordField.addActionListener(this::senhaPasswordFieldActionPerformed);

        mostrarSenhaBox.setText("Mostrar Senha");
        mostrarSenhaBox.addActionListener(this::mostrarSenhaBoxActionPerformed);

        jButton1.setText("Termos de Uso");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(etecVermelhoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(senhaPasswordField)
                                .addComponent(senhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mostrarSenhaBox)
                            .addComponent(jButton1))
                        .addGap(59, 59, 59))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)))
                .addComponent(mauaVermelhoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mauaVermelhoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(etecVermelhoPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(senhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarSenhaBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addComponent(entrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarSenhaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSenhaBoxActionPerformed
        // TODO add your handling code here:
        if (mostrarSenhaBox.isSelected()) {
            senhaPasswordField.setEchoChar((char)0);
        }else{
            senhaPasswordField.setEchoChar('*');
        }   
    }//GEN-LAST:event_mostrarSenhaBoxActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        // TODO add yo  ur handling code here:
        if (numTela == 1){
        String email = emailField.getText().trim();
        String senhaDigitada = new String(senhaPasswordField.getPassword());
        
        if(email.isEmpty() || senhaDigitada.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o email e a senha");
        }
        
        try {
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco");
                return;
            }
            
            String sql = "SELECT * FROM usuarios WHERE email = ?";
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setString(1, email);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                String hashSalvo = rs.getString("senha_hash");
                
                if (SegurancaSenha.verificarSenha(senhaDigitada,hashSalvo)){
                    String nome = rs.getString("nome");
                    String tipoUsuario = rs.getString("tipo_usuario");
                    String idAluno = rs.getString("id_usuario");
                    
                    if(tipoUsuario.equals("Professor")){
                        TelaProfessor tela = new TelaProfessor();
                        tela.setVisible(true);
                        this.dispose();
                        
                    }else if(tipoUsuario.equals("Aluno")){
                        TelaAluno tela = new TelaAluno(nome, idAluno);
                        tela.setVisible(true);
                        this.dispose();
                }
            }else{
                    JOptionPane.showMessageDialog(null, "Email ou senha incorretos.");
                }
            
        }else{JOptionPane.showMessageDialog(null, "Email ou senha incorretos.");
            }
        conexao.close();
        }catch(Exception e){ JOptionPane.showMessageDialog(null, "Erro no login: " + e.getMessage());
        }
        }else{
            JOptionPane.showMessageDialog(null, "Ler os termos de uso primeiro");
        }
        
        
    }//GEN-LAST:event_entrarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String mensagem =  "1. Objeto\n" +
    "A presente plataforma consiste em um jogo educacional voltado ao ensino de Química no nível médio, com a finalidade de...\n\n" +
    "2. Público-alvo\n" +
    "A plataforma é destinada prioritariamente a estudantes do ensino médio, podendo igualmente ser utilizada por docentes...\n" +
    "Nos casos em que o usuário for menor de idade, recomenda-se a utilização com ciência e acompanhamento de seus responsáveis.\n\n" +
    "3. Condições de utilização\n" +
    "Ao utilizar a plataforma, o usuário compromete-se a:\n" +
    "- fazer uso do sistema de maneira ética e exclusivamente para fins educacionais;\n" +
    "- respeitar as normas e instruções de funcionamento disponibilizadas;\n" +
    "- fornecer informações corretas e atualizadas, quando aplicável;\n" +
    "- preservar a integridade da plataforma e de seus recursos;\n" +
    "- manter conduta respeitosa durante toda a utilização do ambiente digital.\n\n" +
    "O uso da plataforma pressupõe a observância integral destes Termos." +
    "4. Restrições de uso\n" +
    "É expressamente vedado ao usuário:\n" +
    "copiar, reproduzir, distribuir ou divulgar qualquer conteúdo da plataforma sem autorização prévia;\n" +
    "alterar, modificar ou tentar comprometer o funcionamento do sistema;\n" +
    "acessar áreas restritas sem permissão;\n" +
    "utilizar a plataforma para fins ilícitos, indevidos ou incompatíveis com sua finalidade educacional;\n" +
    "praticar condutas que prejudiquem outros usuários ou comprometam a segurança do ambiente digital.\n" +
    "O descumprimento destas disposições poderá acarretar a suspensão temporária ou definitiva do acesso à plataforma.\n" +
    "5. Conteúdo educacional e responsabilidade\n" +
    "Os conteúdos disponibilizados foram desenvolvidos com base em princípios científicos e pedagógicos aplicáveis ao ensino médio.\n" +
    "Embora haja compromisso com a qualidade e a atualização das informações apresentadas, a plataforma poderá passar por revisões, atualizações e ajustes sempre que necessário.\n" +
    "O jogo possui caráter complementar e não substitui aulas, materiais didáticos oficiais ou a orientação pedagógica fornecida por profissionais da educação.\n" +
    "6. Propriedade intelectual\n" +
    "Todos os direitos relacionados à plataforma, incluindo textos, imagens, ilustrações, atividades, recursos visuais, interface e demais conteúdos disponibilizados, são de titularidade de seus desenvolvedores e encontram-se protegidos pela legislação vigente relativa à propriedade intelectual e aos direitos autorais.\n" +
    "É vedada qualquer reprodução parcial ou integral sem autorização expressa.\n" +
    "7. Privacidade e proteção de dados\n" +
    "Caso a plataforma realize coleta de informações necessárias ao funcionamento do sistema, tais dados serão utilizados exclusivamente para fins pedagógicos, administrativos ou de melhoria da experiência do usuário.\n" +
    "As informações eventualmente fornecidas serão tratadas com responsabilidade e confidencialidade, não sendo compartilhadas com terceiros, salvo em hipóteses previstas em lei.\n" +
    "8. Alterações dos Termos de Uso\n" +
    "A administração da plataforma reserva-se o direito de modificar, revisar ou atualizar estes Termos de Uso a qualquer momento, conforme necessidade técnica, pedagógica ou administrativa.\n" +
    "As alterações entrarão em vigor a partir de sua publicação no ambiente digital.\n" +
    "9. Disposições finais\n" +
    "A utilização da plataforma implica ciência e concordância integral com todas as condições estabelecidas neste documento.\n" +
    "Ao acessar e utilizar o jogo educacional de Química, o usuário reconhece estar de acordo com as normas previstas e compromete-se a respeitá-las integralmente.\n" +
    "Equipe responsável pelo desenvolvimento do projeto";
    javax.swing.JOptionPane.showMessageDialog(this, mensagem, "Termos de Uso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    numTela = 1;
          
            
                

            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton entrarButton;
    private javax.swing.JPanel etecCinzaPane;
    private javax.swing.JLabel etecLabel;
    private javax.swing.JPanel etecVermelhoPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mauaCinzaPane;
    private javax.swing.JLabel mauaLabel;
    private javax.swing.JPanel mauaVermelhoPane;
    private javax.swing.JCheckBox mostrarSenhaBox;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaPasswordField;
    // End of variables declaration//GEN-END:variables
}
