/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danda
 */
public class TelaJogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJogo.class.getName());
    private String modoJogo;
    private ArrayList< PerguntaJogo > perguntas = new ArrayList<>();
    private int indicePerguntaAtual = 0;
    private int pontuacao = 0;
    private PerguntaJogo perguntaAtual;
    private String nome;
    private int idAluno;
    private boolean respondeuPergunta = false;
    
    private int idPartida;
    
    private boolean usouDicaNaPergunta = false;

    /**
     * Creates new form TelaDificuldade
     */
    public TelaJogo(String modoJogo, String nome, int idAluno) {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.modoJogo = modoJogo;
        this.nome = nome;
        this.idAluno = idAluno;
        
        criarPartida();
        carregarPerguntas();
        mostrarPerguntaAtual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();
        resposta3 = new javax.swing.JButton();
        resposta2 = new javax.swing.JButton();
        resposta4 = new javax.swing.JButton();
        resposta1 = new javax.swing.JButton();
        imagemPergunta = new javax.swing.JLabel();
        imagemResposta2 = new javax.swing.JLabel();
        imagemResposta1 = new javax.swing.JLabel();
        imagemResposta3 = new javax.swing.JLabel();
        imagemResposta4 = new javax.swing.JLabel();
        numeroPergunta = new javax.swing.JLabel();
        nomePontos = new javax.swing.JLabel();
        variavelPontos = new javax.swing.JLabel();
        botãoVoltar = new javax.swing.JButton();
        botãoDica = new javax.swing.JButton();
        botãoPular = new javax.swing.JButton();
        botãoSom = new javax.swing.JButton();
        títuloPergunta = new javax.swing.JLabel();
        avancarButton = new javax.swing.JButton();
        nomePERGUNTA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));
        cinzaPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(255, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(220, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        resposta3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resposta3.setText("Alternativa 3");
        resposta3.addActionListener(this::resposta3ActionPerformed);

        resposta2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resposta2.setText("Alternativa 2");
        resposta2.addActionListener(this::resposta2ActionPerformed);

        resposta4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resposta4.setText("Alternativa 4");
        resposta4.addActionListener(this::resposta4ActionPerformed);

        resposta1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resposta1.setText("Alternativa 1");
        resposta1.addActionListener(this::resposta1ActionPerformed);

        imagemPergunta.setText("IMAGEM PERGUNTA");
        imagemPergunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagemResposta2.setText("IMAGEM 2");
        imagemResposta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagemResposta1.setText("IMAGEM 1");
        imagemResposta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagemResposta3.setText("IMAGEM 3");
        imagemResposta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imagemResposta4.setText("IMAGEM 4");
        imagemResposta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        numeroPergunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        numeroPergunta.setText(" X");

        nomePontos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomePontos.setText("Pontos:");

        variavelPontos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        variavelPontos.setText("X");

        botãoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoVoltar.setText("Voltar ao Menu");
        botãoVoltar.addActionListener(this::botãoVoltarActionPerformed);

        botãoDica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoDica.setText("Ajuda");
        botãoDica.addActionListener(this::botãoDicaActionPerformed);

        botãoPular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoPular.setText("Pular");
        botãoPular.addActionListener(this::botãoPularActionPerformed);

        botãoSom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoSom.setText("Som");
        botãoSom.addActionListener(this::botãoSomActionPerformed);

        títuloPergunta.setText("PERGUNTA");
        títuloPergunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51)));

        avancarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avancarButton.setText("Avançar");
        avancarButton.addActionListener(this::avancarButtonActionPerformed);

        nomePERGUNTA.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomePERGUNTA.setText("Pergunta:");

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(imagemResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(imagemResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(resposta3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                                .addComponent(resposta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(títuloPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addComponent(nomePERGUNTA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroPergunta)))
                        .addGap(263, 263, 263)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addComponent(imagemPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomePontos)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                                        .addComponent(variavelPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGap(57, 57, 57))
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imagemResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(resposta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                                        .addComponent(imagemResposta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resposta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addComponent(botãoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(avancarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                        .addComponent(botãoDica, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botãoPular, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addComponent(vermelhoPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addComponent(nomePontos)
                        .addGap(18, 18, 18)
                        .addComponent(variavelPontos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nomePERGUNTA)
                                    .addComponent(numeroPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(99, 99, 99)
                                .addComponent(títuloPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imagemPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagemResposta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagemResposta1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resposta2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(resposta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagemResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagemResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botãoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avancarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botãoDica, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botãoPular, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta3ActionPerformed
        // TODO add your handling code here:
        responder(2);
    }//GEN-LAST:event_resposta3ActionPerformed

    private void resposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta2ActionPerformed
        // TODO add your handling code here:
        responder(1);
    }//GEN-LAST:event_resposta2ActionPerformed

    private void resposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta4ActionPerformed
        // TODO add your handling code here:
        responder(3);
    }//GEN-LAST:event_resposta4ActionPerformed

    private void resposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta1ActionPerformed
        // TODO add your handling code here:
        responder(0);
    }//GEN-LAST:event_resposta1ActionPerformed

    private void botãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoVoltarActionPerformed
        // TODO add your handling code here:
    int opcao = JOptionPane.showConfirmDialog(
            this,
            "Deseja sair da partida? Ela será marcada como ABANDONADA.",
            "Confirmar saída",
            JOptionPane.YES_NO_OPTION
    );

    if (opcao == JOptionPane.YES_OPTION) {
        TelaAluno tela = new TelaAluno(nome, idAluno);
        tela.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_botãoVoltarActionPerformed

    private void avancarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarButtonActionPerformed
        // TODO add your handling code here:
        
        if (!respondeuPergunta) {
        JOptionPane.showMessageDialog(null, "Responda a pergunta antes de avançar.");
        return;
    }
        indicePerguntaAtual++;
        usouDicaNaPergunta = false;
        mostrarPerguntaAtual();
    }//GEN-LAST:event_avancarButtonActionPerformed

    private void botãoDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoDicaActionPerformed
        // TODO add your handling code here:
        if(perguntaAtual != null){
            usouDicaNaPergunta = true;
            JOptionPane.showMessageDialog(null, perguntaAtual.dica);    
        }
    }//GEN-LAST:event_botãoDicaActionPerformed

    private void botãoPularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoPularActionPerformed
        // TODO add your handling code here:
            indicePerguntaAtual++;
            usouDicaNaPergunta = false;
            mostrarPerguntaAtual();
            
    }//GEN-LAST:event_botãoPularActionPerformed

    private void botãoSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSomActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_botãoSomActionPerformed
    private void carregarPerguntas(){
        perguntas.clear();
        
        if(modoJogo.equals("shuffle")){
            carregarPerguntaPorDificuldade("facil", 3);
            carregarPerguntaPorDificuldade("medio", 3);
            carregarPerguntaPorDificuldade("dificil", 4);
        }else{
            carregarPerguntaPorDificuldade(modoJogo, 10);
        }
    }
    private void carregarPerguntaPorDificuldade(String modoJogo, int limite){
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco");
                return;
            }
            String sql = "SELECT id_pergunta, enunciado, dificuldade, dica, pontos, imagem_path FROM perguntas WHERE dificuldade = ? ORDER BY RAND() LIMIT ?";
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setString(1, modoJogo);
            ps.setInt(2, limite);
            
            ResultSet rs = ps.executeQuery();
            

            while (rs.next()) {
                PerguntaJogo pergunta = new PerguntaJogo();

                pergunta.idPergunta = rs.getInt("id_pergunta");
                pergunta.enunciado = rs.getString("enunciado");
                pergunta.dificuldade = rs.getString("dificuldade");
                pergunta.dica = rs.getString("dica");
                pergunta.pontos = rs.getInt("pontos");
                pergunta.imagemPath = rs.getString("imagem_path");

                carregarAlternativas(pergunta, conexao);

                perguntas.add(pergunta);
            }
            conexao.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco" + e.getMessage());
        }
    }
    
    private void carregarAlternativas(PerguntaJogo pergunta, Connection conexao)throws Exception{
        String sql = "SELECT id_alternativa, texto, imagem_path, correta, ordem FROM alternativas WHERE id_pergunta = ? ORDER BY ordem";
        
        PreparedStatement ps = conexao.prepareStatement(sql);
        ps.setInt(1, pergunta.idPergunta);
        
        ResultSet rs = ps.executeQuery();
        
        while(rs.next()){
            AlternativaJogo alt = new AlternativaJogo();
            
            alt.idAlternativa = rs.getInt("id_alternativa");
            alt.texto = rs.getString("texto");
            alt.imagemPath = rs.getString("imagem_path");
            alt.correta = rs.getBoolean("correta");
            alt.ordem = rs.getInt("ordem");
            
            pergunta.alternativas.add(alt);
        }
    }
    
    private void mostrarPerguntaAtual() {
        if (perguntas.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Não existem perguntas cadastradas para este modo.");
        return;
        }

        if (indicePerguntaAtual >= perguntas.size()) {
            finalizarPartida();
            JOptionPane.showMessageDialog(null, "Fim do jogo! Pontuação final: " + pontuacao);

            TelaAluno tela = new TelaAluno(nome,idAluno);
            tela.setVisible(true);
            this.dispose();
            return;
        }

        perguntaAtual = perguntas.get(indicePerguntaAtual);

        numeroPergunta.setText("" + (indicePerguntaAtual + 1));

        títuloPergunta.setText(perguntaAtual.enunciado);

        variavelPontos.setText(String.valueOf(pontuacao));

        limparCoresBotoes();
        habilitarBotoes(true);
        limparImagensAlternativas();

        if (perguntaAtual.imagemPath != null && !perguntaAtual.imagemPath.isEmpty()) {
            mostrarImagemNoLabel(perguntaAtual.imagemPath, imagemPergunta);
        } else {
            imagemPergunta.setIcon(null);
            imagemPergunta.setText("IMAGEM PERGUNTA");
        }

        if (perguntaAtual.alternativas.size() < 4) {
            JOptionPane.showMessageDialog(null, "Essa pergunta não tem 4 alternativas cadastradas.");
            return;
        }

        resposta1.setText(perguntaAtual.alternativas.get(0).texto);
        resposta2.setText(perguntaAtual.alternativas.get(1).texto);
        resposta3.setText(perguntaAtual.alternativas.get(2).texto);
        resposta4.setText(perguntaAtual.alternativas.get(3).texto);

        carregarImagemAlternativa(0, imagemResposta1);
        carregarImagemAlternativa(1, imagemResposta2);
        carregarImagemAlternativa(2, imagemResposta3);
        carregarImagemAlternativa(3, imagemResposta4);

        repaint();
        revalidate();
        
        respondeuPergunta = false;
        avancarButton.setEnabled(false);
    }
    private void limparImagensAlternativas() {
        imagemResposta1.setIcon(null);
        imagemResposta1.setText("");

        imagemResposta2.setIcon(null);
        imagemResposta2.setText("");

        imagemResposta3.setIcon(null);
        imagemResposta3.setText("");

        imagemResposta4.setIcon(null);
        imagemResposta4.setText("");
    }
    
    private void carregarImagemAlternativa(int indice, javax.swing.JLabel label){
        String caminho = perguntaAtual.alternativas.get(indice).imagemPath;
        
        if(caminho != null && !caminho.isEmpty()){
            mostrarImagemNoLabel(caminho, label);
        }else{
            label.setIcon(null);
            label.setText("");
        }
    }
    
    private void mostrarImagemNoLabel(String caminho, javax.swing.JLabel label){
        ImageIcon icon = new ImageIcon(caminho);
        Image img = icon.getImage();
        
        Image imgRedimensionada = img.getScaledInstance(
                label.getWidth(),
                label.getHeight(),
                Image.SCALE_SMOOTH
        );
        
        label.setText("");
        label.setIcon(new ImageIcon(imgRedimensionada));
    }
    
    private void responder(int indiceEscolhido){
        AlternativaJogo escolhida = perguntaAtual.alternativas.get(indiceEscolhido);
        
        if(escolhida.correta){
            pontuacao += perguntaAtual.pontos;
        }
        
        salvarResposta(escolhida);
        
        pintarAlternativas(indiceEscolhido);
        variavelPontos.setText(String.valueOf(pontuacao));
        
        habilitarBotoes(false);
        
        respondeuPergunta = true;
        avancarButton.setEnabled(true);
    }
    
    private void limparCoresBotoes(){
        javax.swing.JButton[] botoes = {
            resposta1,
            resposta2,
            resposta3,
            resposta4,
        };
        
        for (javax.swing.JButton botao : botoes){
            botao.setBackground(null);
            botao.setForeground(Color.BLACK);
            botao.setOpaque(true);
            botao.setContentAreaFilled(true);
        }
    }
    
    private void habilitarBotoes(boolean habilitar){
        resposta1.setEnabled(habilitar);
        resposta2.setEnabled(habilitar);
        resposta3.setEnabled(habilitar);
        resposta4.setEnabled(habilitar);
    }
    
    private void pintarAlternativas(int indiceEscolhido){
         javax.swing.JButton[] botoes = {
             resposta1,
             resposta2,
             resposta3,
             resposta4
         };
         
         for(int i=0; i < perguntaAtual.alternativas.size(); i++){
             AlternativaJogo alt = perguntaAtual.alternativas.get(i);
             
             if(alt.correta){
                 botoes[i].setBackground(Color.GREEN);
             }else{
                 botoes[i].setBackground(Color.RED);
             }
             
             botoes[i].setOpaque(true);
             botoes[i].setContentAreaFilled(true);
             botoes[i].setForeground(Color.WHITE);
         }
    }
    
    private void criarPartida(){
        try {
           ConnectionFactory c = new ConnectionFactory();
           Connection conexao = c.obtemConexao();

           if (conexao == null) {
               JOptionPane.showMessageDialog(null, "Falha na conexão com o banco.");
               return;
           }

           String nivelAlcancado;

           if (modoJogo.equals("facil")) {
               nivelAlcancado = "FACIL";
           } else if (modoJogo.equals("medio")) {
               nivelAlcancado = "MEDIO";
           } else {
               nivelAlcancado = "DIFICIL";
           }

           String sql = "INSERT INTO partidas (id_aluno, modo_jogo, status_partida, nivel_alcancado) VALUES (?, ?, ?, ?)";

           PreparedStatement ps = conexao.prepareStatement(
                   sql,
                   java.sql.Statement.RETURN_GENERATED_KEYS
           );

           ps.setInt(1, idAluno);
           ps.setString(2, modoJogo);
           ps.setString(3, "ABANDONADA");
           ps.setString(4, nivelAlcancado);

           ps.executeUpdate();

           ResultSet rs = ps.getGeneratedKeys();

           if (rs.next()) {
               idPartida = rs.getInt(1);
           }

           conexao.close();

       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Erro ao criar partida: " + e.getMessage());
       }
    }
    
    private void salvarResposta(AlternativaJogo alternativaEscolhida){
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco.");
                return;
            }
            
            int pontosObtidos = 0;
            
            if(alternativaEscolhida.correta){
                pontosObtidos = perguntaAtual.pontos;
            }
            
            String sql = "INSERT INTO respostas_partida (id_partida, id_pergunta, id_alternativa, acertou, usou_dica, pontos_obtidos) VALUE (?,?,?,?,?,?)";
            
            PreparedStatement ps = conexao.prepareStatement(sql);
            
            ps.setInt(1,idPartida);
            ps.setInt(2,perguntaAtual.idPergunta);
            ps.setInt(3,alternativaEscolhida.idAlternativa);
            ps.setBoolean(4, alternativaEscolhida.correta);
            ps.setBoolean(5, usouDicaNaPergunta);
            ps.setInt(6, pontosObtidos);
            
            ps.executeUpdate();
            
            conexao.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao salvar resposta: " + e.getMessage());
        }
    }
    
    private void finalizarPartida(){
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco.");
                return;
            }
            
            String sql = "UPDATE partidas SET status_partida = ? WHERE id_partida = ?";
            
            PreparedStatement ps = conexao.prepareStatement(sql);
            
            ps.setString(1, "FINALIZADA");
            ps.setInt(2, idPartida);
            
            ps.executeUpdate();
            
            conexao.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao finalizar partida: " + e.getMessage());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJogo("","",1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avancarButton;
    private javax.swing.JButton botãoDica;
    private javax.swing.JButton botãoPular;
    private javax.swing.JButton botãoSom;
    private javax.swing.JButton botãoVoltar;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JLabel imagemPergunta;
    private javax.swing.JLabel imagemResposta1;
    private javax.swing.JLabel imagemResposta2;
    private javax.swing.JLabel imagemResposta3;
    private javax.swing.JLabel imagemResposta4;
    private javax.swing.JLabel nomePERGUNTA;
    private javax.swing.JLabel nomePontos;
    private javax.swing.JLabel numeroPergunta;
    private javax.swing.JButton resposta1;
    private javax.swing.JButton resposta2;
    private javax.swing.JButton resposta3;
    private javax.swing.JButton resposta4;
    private javax.swing.JLabel títuloPergunta;
    private javax.swing.JLabel variavelPontos;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
