/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author danda
 */
public class TelaEdiçãoPergunta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEdiçãoPergunta.class.getName());
    
    private int idPergunta;
    
    private int idAlternativa1;
    private int idAlternativa2;
    private int idAlternativa3;
    private int idAlternativa4;
    
    private String imagemPerguntaPath = null;
    private String imagemResposta1Path = null;
    private String imagemResposta2Path = null;
    private String imagemResposta3Path = null;
    private String imagemResposta4Path = null;

    /**
     * Creates new form TelaDificuldade
     */
    public TelaEdiçãoPergunta(int idPergunta) {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        
        this.idPergunta = idPergunta;
        
        botãoDificuldade.removeAllItems();
        botãoDificuldade.addItem("facil");
        botãoDificuldade.addItem("medio");
        botãoDificuldade.addItem("dificil");
        
        botãoAlternaticaCorreta.removeAllItems();
        botãoAlternaticaCorreta.addItem("Resposta 1");
        botãoAlternaticaCorreta.addItem("Resposta 2");
        botãoAlternaticaCorreta.addItem("Resposta 3");
        botãoAlternaticaCorreta.addItem("Resposta 4");
        
        configurarSelecaoImagens();
        carregarDadosPergunta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        botãoFecharTotal = new javax.swing.JButton();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();
        botãoAtualizar = new javax.swing.JButton();
        botãoSair = new javax.swing.JButton();
        cadastrarDica = new javax.swing.JTextField();
        dica = new javax.swing.JLabel();
        cadastrarResposta3 = new javax.swing.JTextField();
        cadastrarResposta4 = new javax.swing.JTextField();
        cadastrarImagem4 = new javax.swing.JLabel();
        cadastrarImagem3 = new javax.swing.JLabel();
        resposta4 = new javax.swing.JLabel();
        resposta3 = new javax.swing.JLabel();
        cadastrarResposta2 = new javax.swing.JTextField();
        cadastrarResposta1 = new javax.swing.JTextField();
        cadastrarImagem2 = new javax.swing.JLabel();
        cadastrarImagem1 = new javax.swing.JLabel();
        resposta2 = new javax.swing.JLabel();
        reposta1 = new javax.swing.JLabel();
        cadastrarImagemPergunta = new javax.swing.JLabel();
        cadastrarPergunta = new javax.swing.JTextField();
        identificadorPergunta = new javax.swing.JLabel();
        nomePágina = new javax.swing.JLabel();
        botãoSom = new javax.swing.JButton();
        botãoDificuldade = new javax.swing.JComboBox<>();
        botãoExcluir = new javax.swing.JButton();
        botãoAlternaticaCorreta = new javax.swing.JComboBox<>();
        DificuldadeLabel = new javax.swing.JLabel();
        RespostaCorretaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));
        cinzaPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(255, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        botãoFecharTotal.setText("X");
        botãoFecharTotal.addActionListener(this::botãoFecharTotalActionPerformed);

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botãoFecharTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botãoFecharTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(220, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botãoAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoAtualizar.setText("Atualizar");
        botãoAtualizar.addActionListener(this::botãoAtualizarActionPerformed);

        botãoSair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoSair.setText("Voltar");
        botãoSair.addActionListener(this::botãoSairActionPerformed);

        dica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dica.setText("Dica:");

        cadastrarResposta4.addActionListener(this::cadastrarResposta4ActionPerformed);

        cadastrarImagem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem4.setText("Colocar Imagem da Pergunta 4");
        cadastrarImagem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadastrarImagem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem3.setText("Colocar Imagem da Pergunta 3");
        cadastrarImagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resposta4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resposta4.setText("Resposta 4");

        resposta3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resposta3.setText("Resposta 3");

        cadastrarResposta2.addActionListener(this::cadastrarResposta2ActionPerformed);

        cadastrarResposta1.addActionListener(this::cadastrarResposta1ActionPerformed);

        cadastrarImagem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem2.setText("Colocar Imagem da Pergunta 2");
        cadastrarImagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadastrarImagem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem1.setText("Colocar Imagem da Pergunta 1");
        cadastrarImagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resposta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resposta2.setText("Resposta 2");

        reposta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reposta1.setText("Resposta 1");

        cadastrarImagemPergunta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagemPergunta.setText("Colocar Imagem Pergunta");
        cadastrarImagemPergunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        identificadorPergunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        identificadorPergunta.setText("Pergunta");

        nomePágina.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nomePágina.setText("Edição de Perguntas");

        botãoSom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoSom.setText("Som");
        botãoSom.addActionListener(this::botãoSomActionPerformed);

        botãoDificuldade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botãoDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botãoExcluir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoExcluir.setText("Excluir");
        botãoExcluir.addActionListener(this::botãoExcluirActionPerformed);

        botãoAlternaticaCorreta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botãoAlternaticaCorreta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        botãoAlternaticaCorreta.addActionListener(this::botãoAlternaticaCorretaActionPerformed);

        DificuldadeLabel.setText("Dificuldades:");

        RespostaCorretaLabel.setText("Resposta Correta:");

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomePágina)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botãoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(identificadorPergunta)
                                        .addComponent(cadastrarPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                        .addComponent(cadastrarImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cadastrarResposta1)
                                        .addComponent(cadastrarImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reposta1)
                                        .addComponent(resposta3)
                                        .addComponent(cadastrarResposta3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addComponent(cadastrarImagemPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(285, 285, 285)
                                .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadastrarImagem2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resposta2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrarImagem4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resposta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botãoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cadastrarResposta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                    .addComponent(cadastrarResposta2, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGap(807, 807, 807)
                                .addComponent(dica))
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGap(499, 499, 499)
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                                        .addComponent(DificuldadeLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cadastrarDica, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                                        .addComponent(botãoDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(115, 115, 115)
                                        .addComponent(botãoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)))
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RespostaCorretaLabel)
                                    .addComponent(botãoAlternaticaCorreta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nomePágina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(identificadorPergunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cadastrarImagemPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reposta1)
                    .addComponent(resposta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrarResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarImagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resposta3)
                    .addComponent(resposta4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dica)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarDica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botãoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DificuldadeLabel)
                            .addComponent(RespostaCorretaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botãoExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(botãoDificuldade)
                            .addComponent(botãoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botãoAlternaticaCorreta))))
                .addGap(23, 23, 23))
            .addComponent(vermelhoPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botãoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoAtualizarActionPerformed
        // TODO add your handling code here:
        String pergunta = cadastrarPergunta.getText().trim();
        String resposta1 = cadastrarResposta1.getText().trim();
        String resposta2 = cadastrarResposta2.getText().trim();
        String resposta3 = cadastrarResposta3.getText().trim();
        String resposta4 = cadastrarResposta4.getText().trim();
        String dicaTexto = cadastrarDica.getText().trim();
        
        String dificuldade = botãoDificuldade.getSelectedItem().toString();
        int respostaCorreta = botãoAlternaticaCorreta.getSelectedIndex() +1;
        
        if(pergunta.isEmpty() || resposta1.isEmpty() || resposta2.isEmpty() || resposta3.isEmpty() || resposta4.isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos");
            return;
        }
        
        int pontos;
        if(dificuldade.equals("facil")){
            pontos = 10;
        }else if(dificuldade.equals("medio")){
            pontos = 20;
        }else{
            pontos = 30;
        }
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha ao conectar no banco");
                return;
            }
            
            String sqlPergunta = "UPDATE perguntas SET enunciado = ?, dificuldade = ?, dica = ?, pontos = ?, imagem_path = ? WHERE id_pergunta = ?";
            
            PreparedStatement psPergunta = conexao.prepareStatement(sqlPergunta);
            psPergunta.setString(1, pergunta);
            psPergunta.setString(2, dificuldade);
            psPergunta.setString(3, dicaTexto);
            psPergunta.setInt(4, pontos);
            psPergunta.setString(5, imagemPerguntaPath);
            psPergunta.setInt(6, idPergunta);
            
            psPergunta.executeUpdate();
            
            atualizarAlternativa(conexao, idAlternativa1, resposta1, imagemResposta1Path, respostaCorreta == 1);
            atualizarAlternativa(conexao, idAlternativa2, resposta2, imagemResposta2Path, respostaCorreta == 2);
            atualizarAlternativa(conexao, idAlternativa3, resposta3, imagemResposta3Path, respostaCorreta == 3);
            atualizarAlternativa(conexao, idAlternativa4, resposta4, imagemResposta4Path, respostaCorreta == 4);
            
            JOptionPane.showMessageDialog(null, "Respostas atualizadas com sucesso");
            
            conexao.close();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar pergunta " +e.getMessage());
        }
        
        
    }//GEN-LAST:event_botãoAtualizarActionPerformed

    private void botãoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSairActionPerformed
        // TODO add your handling code here:
        TelaPerguntas tela = new TelaPerguntas();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoSairActionPerformed

    private void cadastrarResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarResposta1ActionPerformed

    private void cadastrarResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResposta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarResposta2ActionPerformed

    private void cadastrarResposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResposta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarResposta4ActionPerformed

    private void botãoAlternaticaCorretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoAlternaticaCorretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botãoAlternaticaCorretaActionPerformed

    private void botãoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir essa pergunta?","Confirmando exclusão",JOptionPane.YES_NO_OPTION);
        if (resposta != JOptionPane.YES_OPTION){
            return;
        }
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco");
            }
            String sql = "DELETE FROM perguntas WHERE id_pergunta = ?";
            
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setInt(1,idPergunta);
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Pergunta excluída com sucesso!");
            
            conexao.close();
            
            TelaPerguntas tela = new TelaPerguntas();
            tela.setVisible(true);
            this.dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar pergunta " +e.getMessage());
        }
    }//GEN-LAST:event_botãoExcluirActionPerformed

    private void botãoSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSomActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_botãoSomActionPerformed

    private void botãoFecharTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoFecharTotalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botãoFecharTotalActionPerformed
    private void configurarSelecaoImagens() {
    cadastrarImagemPergunta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    cadastrarImagemPergunta.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemPerguntaPath = escolherImagem();
            if (imagemPerguntaPath != null) {
                mostrarImagemNoLabel(imagemPerguntaPath, cadastrarImagemPergunta);
            }
        }
    });

    cadastrarImagem1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta1Path = escolherImagem();
            if (imagemResposta1Path != null) {
                mostrarImagemNoLabel(imagemResposta1Path, cadastrarImagem1);
            }
        }
    });

    cadastrarImagem2.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta2Path = escolherImagem();
            if (imagemResposta2Path != null) {
                mostrarImagemNoLabel(imagemResposta2Path, cadastrarImagem2);
            }
        }
    });

    cadastrarImagem3.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta3Path = escolherImagem();
            if (imagemResposta3Path != null) {
                mostrarImagemNoLabel(imagemResposta3Path, cadastrarImagem3);
            }
        }
    });

    cadastrarImagem4.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta4Path = escolherImagem();
            if (imagemResposta4Path != null) {
                mostrarImagemNoLabel(imagemResposta4Path, cadastrarImagem4);
            }
        }
    });
}
    
    private String escolherImagem(){
        JFileChooser chooser = new JFileChooser();
       chooser.setDialogTitle("Selecionar imagem");
       
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens (*.jpg, *.jpeg, *.png)","jpg","jpeg", "png");
       chooser.setFileFilter(filtro);
       int resultado = chooser.showOpenDialog(this);
       if(resultado == JFileChooser.APPROVE_OPTION){
           File arquivo = chooser.getSelectedFile();
           return arquivo.getAbsolutePath();
       }
       return null;
    }
    
    private void mostrarImagemNoLabel(String caminho,javax.swing.JLabel label){
        ImageIcon icon = new ImageIcon(caminho);
        Image img = icon.getImage();
        
        Image imgRedimensionada = img.getScaledInstance(
        label.getWidth(),
        label.getHeight(),
        Image.SCALE_SMOOTH);
        label.setText("");
        label.setIcon(new ImageIcon(imgRedimensionada));
    };
    private void carregarDadosPergunta(){
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null,"Falha na conexão com o branco");
                return;
            }
            
            String sqlPergunta = "SELECT enunciado, dificuldade, dica, imagem_path FROM perguntas WHERE id_pergunta = ?";
            
            PreparedStatement psPergunta = conexao.prepareStatement(sqlPergunta);
            psPergunta.setInt(1, idPergunta);
            
            ResultSet rsPergunta = psPergunta.executeQuery();
            
            if (rsPergunta.next()){
                cadastrarPergunta.setText(rsPergunta.getString("enunciado"));
                cadastrarDica.setText(rsPergunta.getString("dica"));
                
                String dificuldade = rsPergunta.getString("dificuldade");
                botãoDificuldade.setSelectedItem(dificuldade);
                
                imagemPerguntaPath = rsPergunta.getString("imagem_path");
                
                if(imagemPerguntaPath != null && !imagemPerguntaPath.isEmpty()){
                    mostrarImagemNoLabel(imagemPerguntaPath, cadastrarImagemPergunta);
                }
            }
            
            String sqlAlternativa = "SELECT id_alternativa, texto, imagem_path, correta, ordem FROM alternativas WHERE id_pergunta = ? ORDER BY ordem";
            
            PreparedStatement psAlt = conexao.prepareStatement(sqlAlternativa);
            psAlt.setInt(1, idPergunta);
            
            ResultSet rsAlt = psAlt.executeQuery();
            
            while (rsAlt.next()) {
                int ordem = rsAlt.getInt("ordem");
                int idAlternativa = rsAlt.getInt("id_alternativa");
                String texto = rsAlt.getString("texto");
                String imagem = rsAlt.getString("imagem_path");
                boolean correta = rsAlt.getBoolean("correta");

                switch (ordem) {
                    case 1:
                        idAlternativa1 = idAlternativa;
                        cadastrarResposta1.setText(texto);
                        imagemResposta1Path = imagem;

                        if (imagem != null && !imagem.isEmpty()) {
                            mostrarImagemNoLabel(imagem, cadastrarImagem1);
                        }
                        break;

                    case 2:
                        idAlternativa2 = idAlternativa;
                        cadastrarResposta2.setText(texto);
                        imagemResposta2Path = imagem;

                        if (imagem != null && !imagem.isEmpty()) {
                        mostrarImagemNoLabel(imagem, cadastrarImagem2);
                        }
                        break;

                    case 3:
                        idAlternativa3 = idAlternativa;
                        cadastrarResposta3.setText(texto);
                        imagemResposta3Path = imagem;

                        if (imagem != null && !imagem.isEmpty()) {
                            mostrarImagemNoLabel(imagem, cadastrarImagem3);
                        }
                        break;

                    case 4:
                        idAlternativa4 = idAlternativa;
                        cadastrarResposta4.setText(texto);
                        imagemResposta4Path = imagem;

                        if (imagem != null && !imagem.isEmpty()) {
                        mostrarImagemNoLabel(imagem, cadastrarImagem4);
                        }
                        break;
                    }

                    if (correta) {
                        botãoAlternaticaCorreta.setSelectedIndex(ordem - 1);
                    }
}
            rsAlt.close();
            psAlt.close();
            conexao.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao carregar pergunta " +e.getMessage());
        }
    }
    
    private void atualizarAlternativa( Connection conexao, int idAlternativa, String texto, String imagemPath, boolean correta)throws Exception{
        String sql = "UPDATE alternativas SET texto = ?, imagem_path = ?, correta = ? WHERE id_alternativa = ?";
        PreparedStatement ps = conexao.prepareStatement(sql);
        ps.setString(1, texto);
        ps.setString(2,imagemPath);
        ps.setBoolean(3, correta);
        ps.setInt(4, idAlternativa);
        
        ps.executeUpdate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEdiçãoPergunta(1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DificuldadeLabel;
    private javax.swing.JLabel RespostaCorretaLabel;
    private javax.swing.JComboBox<String> botãoAlternaticaCorreta;
    private javax.swing.JButton botãoAtualizar;
    private javax.swing.JComboBox<String> botãoDificuldade;
    private javax.swing.JButton botãoExcluir;
    private javax.swing.JButton botãoFecharTotal;
    private javax.swing.JButton botãoSair;
    private javax.swing.JButton botãoSom;
    private javax.swing.JTextField cadastrarDica;
    private javax.swing.JLabel cadastrarImagem1;
    private javax.swing.JLabel cadastrarImagem2;
    private javax.swing.JLabel cadastrarImagem3;
    private javax.swing.JLabel cadastrarImagem4;
    private javax.swing.JLabel cadastrarImagemPergunta;
    private javax.swing.JTextField cadastrarPergunta;
    private javax.swing.JTextField cadastrarResposta1;
    private javax.swing.JTextField cadastrarResposta2;
    private javax.swing.JTextField cadastrarResposta3;
    private javax.swing.JTextField cadastrarResposta4;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JLabel dica;
    private javax.swing.JLabel identificadorPergunta;
    private javax.swing.JLabel nomePágina;
    private javax.swing.JLabel reposta1;
    private javax.swing.JLabel resposta2;
    private javax.swing.JLabel resposta3;
    private javax.swing.JLabel resposta4;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
