/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author danda
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());
    
    private String imagemPerguntaPath = null;
    private String imagemResposta1Path = null;
    private String imagemResposta2Path = null;
    private String imagemResposta3Path = null;
    private String imagemResposta4Path = null;




    /**
     * Creates new form TelaDificuldade
     */
    public TelaCadastro() {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        botãoDificuldade.removeAllItems();
        botãoDificuldade.addItem("facil");
        botãoDificuldade.addItem("medio");
        botãoDificuldade.addItem("dificil");
        
        CorretaBox.removeAllItems();
        CorretaBox.addItem("Resposta 1");
        CorretaBox.addItem("Resposta 2");
        CorretaBox.addItem("Resposta 3");
        CorretaBox.addItem("Resposta 4");
        configurarSelecaoImagens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        botãoFecharTotal = new javax.swing.JButton();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();
        botãoCadastrar = new javax.swing.JButton();
        botãoSair = new javax.swing.JButton();
        cadastrarDica = new javax.swing.JTextField();
        dica = new javax.swing.JLabel();
        cadastrarResposta3 = new javax.swing.JTextField();
        cadastrarResposta4 = new javax.swing.JTextField();
        cadastrarImagem4 = new javax.swing.JLabel();
        cadastrarImagem3 = new javax.swing.JLabel();
        resposta4 = new javax.swing.JLabel();
        resposta3 = new javax.swing.JLabel();
        cadastrarResposta2 = new javax.swing.JTextField();
        cadastrarResposta1 = new javax.swing.JTextField();
        cadastrarImagem2 = new javax.swing.JLabel();
        cadastrarImagem1 = new javax.swing.JLabel();
        resposta2 = new javax.swing.JLabel();
        reposta1 = new javax.swing.JLabel();
        cadastrarImagemPergunta = new javax.swing.JLabel();
        cadastrarPergunta = new javax.swing.JTextField();
        identificadorPergunta = new javax.swing.JLabel();
        nomePágina = new javax.swing.JLabel();
        botãoSom = new javax.swing.JButton();
        botãoDificuldade = new javax.swing.JComboBox<>();
        DificuldadeLabel = new javax.swing.JLabel();
        CorretaBox = new javax.swing.JComboBox<>();
        DificuldadeLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));
        cinzaPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(255, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        botãoFecharTotal.setText("X");
        botãoFecharTotal.addActionListener(this::botãoFecharTotalActionPerformed);

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botãoFecharTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botãoFecharTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(220, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botãoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoCadastrar.setText("Cadastrar");
        botãoCadastrar.addActionListener(this::botãoCadastrarActionPerformed);

        botãoSair.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoSair.setText("Voltar");
        botãoSair.addActionListener(this::botãoSairActionPerformed);

        dica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dica.setText("Dica:");

        cadastrarResposta4.addActionListener(this::cadastrarResposta4ActionPerformed);

        cadastrarImagem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem4.setText("Colocar Imagem da Resposta 4");
        cadastrarImagem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadastrarImagem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem3.setText("Colocar Imagem da Resposta 3");
        cadastrarImagem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resposta4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resposta4.setText("Resposta 4");

        resposta3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resposta3.setText("Resposta 3");

        cadastrarResposta2.addActionListener(this::cadastrarResposta2ActionPerformed);

        cadastrarResposta1.addActionListener(this::cadastrarResposta1ActionPerformed);

        cadastrarImagem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem2.setText("Colocar Imagem da Resposta 2");
        cadastrarImagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cadastrarImagem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagem1.setText("Colocar Imagem da Resposta 1");
        cadastrarImagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resposta2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resposta2.setText("Resposta 2");

        reposta1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reposta1.setText("Resposta 1");

        cadastrarImagemPergunta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarImagemPergunta.setText("Colocar Imagem da Pergunta ");
        cadastrarImagemPergunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        identificadorPergunta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        identificadorPergunta.setText("Pergunta");

        nomePágina.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nomePágina.setText("Cadastro de Perguntas");

        botãoSom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoSom.setText("Som");
        botãoSom.addActionListener(this::botãoSomActionPerformed);

        botãoDificuldade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DificuldadeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificuldadeLabel.setText("Dificuldade:");

        CorretaBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CorretaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DificuldadeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DificuldadeLabel1.setText("Resposta Correta:");

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cadastrarPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                        .addComponent(cadastrarResposta1)
                                        .addComponent(cadastrarResposta3)
                                        .addComponent(nomePágina)
                                        .addComponent(reposta1)
                                        .addComponent(cadastrarImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(identificadorPergunta)
                                        .addComponent(cadastrarImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(resposta3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                                                .addComponent(cadastrarImagemPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(162, 162, 162))
                                            .addComponent(cadastrarImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(resposta2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                        .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(botãoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cadastrarResposta2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                                                .addComponent(cadastrarImagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(resposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cadastrarResposta4)))
                                        .addGap(24, 24, 24))))
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addComponent(botãoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGap(707, 707, 707)
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadastrarDica, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botãoDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DificuldadeLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DificuldadeLabel1)
                                            .addComponent(CorretaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGap(834, 834, 834)
                                .addComponent(dica)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addComponent(nomePágina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(identificadorPergunta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cadastrarPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadastrarImagemPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrarImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reposta1)
                    .addComponent(resposta2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastrarResposta1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cadastrarResposta2))
                .addGap(18, 18, 18)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadastrarImagem4, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(cadastrarImagem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resposta3)
                    .addComponent(resposta4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarResposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(dica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarDica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DificuldadeLabel1)
                    .addComponent(DificuldadeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botãoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botãoDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CorretaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botãoSair, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addComponent(vermelhoPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botãoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoCadastrarActionPerformed
        // TODO add your handling code here:]
        String pergunta = cadastrarPergunta.getText().trim();
        String resposta1 = cadastrarResposta1.getText().trim();
        String resposta2 = cadastrarResposta2.getText().trim();
        String resposta3 = cadastrarResposta3.getText().trim();
        String resposta4 = cadastrarResposta4.getText().trim();
        String dicaTexto = cadastrarDica.getText().trim();
        
        String dificuldade = botãoDificuldade.getSelectedItem().toString();
        int respostaCorreta = CorretaBox.getSelectedIndex() + 1;
        
        int pontos;

        if (dificuldade.equals("facil")) {
            pontos = 10;
        } else if (dificuldade.equals("medio")) {
            pontos = 20;
        } else {
            pontos = 30;
        }
        
        if(pergunta.isEmpty() || resposta1.isEmpty() || resposta2.isEmpty() || resposta3.isEmpty() || resposta4.isEmpty() || dicaTexto.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todas as respostas e as dicas");
            return;
        }
        try{
            ConnectionFactory c = new ConnectionFactory();
            Connection conexao = c.obtemConexao();
            
            if(conexao == null){
                JOptionPane.showMessageDialog(null, "Falha na conexão com o banco.");
                return;
            }
            
            String sql = "INSERT INTO perguntas (enunciado,dificuldade,dica,pontos,imagem_path) VALUES (?,?,?,?,?)";
            
            PreparedStatement ps = conexao.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
            
            ps.setString(1, pergunta);
            ps.setString(2, dificuldade);
            ps.setString(3, dicaTexto);
            ps.setInt(4, pontos);
            ps.setString(5, imagemPerguntaPath);
            
            ps.executeUpdate();
            
            ResultSet rs = ps.getGeneratedKeys();
            
            int idPergunta;
            
            if(rs.next()){
                idPergunta = rs.getInt(1);
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao obter ID da pergunta.");
                conexao.close();
                return;
            }
            
            inserirAlternativa(conexao, idPergunta, resposta1, imagemResposta1Path, respostaCorreta == 1,1);
            inserirAlternativa(conexao, idPergunta, resposta2, imagemResposta2Path, respostaCorreta == 2,2);
            inserirAlternativa(conexao, idPergunta, resposta3, imagemResposta3Path, respostaCorreta == 3,3);
            inserirAlternativa(conexao, idPergunta, resposta4, imagemResposta4Path, respostaCorreta == 4,4);
            
            JOptionPane.showMessageDialog(null, "Pergunta cadastrada com sucesso!");
            
            limparCampos();
            
            conexao.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar pergunta: " + e.getMessage());
        }
        
    }//GEN-LAST:event_botãoCadastrarActionPerformed
    
    private void inserirAlternativa(
        Connection conexao, int idPergunta, String Texto, String imagemPath, boolean correta, int ordem)throws Exception{
        String sql = "INSERT INTO alternativas (id_pergunta, texto, imagem_path, correta, ordem) VALUES (?,?,?,?,?)";
        
        PreparedStatement ps = conexao.prepareStatement(sql);
        ps.setInt(1,idPergunta);
        ps.setString(2,Texto);
        ps.setString(3,imagemPath);
        ps.setBoolean(4, correta);
        ps.setInt(5, ordem);
        
        ps.executeUpdate();
    }
    
    private void limparCampos() {
    cadastrarPergunta.setText("");
    cadastrarResposta1.setText("");
    cadastrarResposta2.setText("");
    cadastrarResposta3.setText("");
    cadastrarResposta4.setText("");
    cadastrarDica.setText("");

    imagemPerguntaPath = null;
    imagemResposta1Path = null;
    imagemResposta2Path = null;
    imagemResposta3Path = null;
    imagemResposta4Path = null;

    cadastrarImagemPergunta.setIcon(null);
    cadastrarImagemPergunta.setText("Colocar Imagem da Pergunta");

    cadastrarImagem1.setIcon(null);
    cadastrarImagem1.setText("Colocar Imagem da Resposta 1");

    cadastrarImagem2.setIcon(null);
    cadastrarImagem2.setText("Colocar Imagem da Resposta 2");

    cadastrarImagem3.setIcon(null);
    cadastrarImagem3.setText("Colocar Imagem da Resposta 3");

    cadastrarImagem4.setIcon(null);
    cadastrarImagem4.setText("Colocar Imagem da Resposta 4");

    botãoDificuldade.setSelectedIndex(0);
    CorretaBox.setSelectedIndex(0);
}
    private void botãoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSairActionPerformed
        // TODO add your handling code here:
        TelaEscolhaPerguntas tela = new TelaEscolhaPerguntas();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoSairActionPerformed

    private void cadastrarResposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarResposta1ActionPerformed

    private void cadastrarResposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResposta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarResposta2ActionPerformed

    private void cadastrarResposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarResposta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarResposta4ActionPerformed

    private void botãoSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSomActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_botãoSomActionPerformed

    private void botãoFecharTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoFecharTotalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botãoFecharTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastro().setVisible(true));
    }
    private void configurarSelecaoImagens() {
    cadastrarImagemPergunta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cadastrarImagem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    cadastrarImagemPergunta.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemPerguntaPath = escolherImagem();
            if (imagemPerguntaPath != null) {
                mostrarImagemNoLabel(imagemPerguntaPath, cadastrarImagemPergunta);
            }
        }
    });

    cadastrarImagem1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta1Path = escolherImagem();
            if (imagemResposta1Path != null) {
                mostrarImagemNoLabel(imagemResposta1Path, cadastrarImagem1);
            }
        }
    });

    cadastrarImagem2.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta2Path = escolherImagem();
            if (imagemResposta2Path != null) {
                mostrarImagemNoLabel(imagemResposta2Path, cadastrarImagem2);
            }
        }
    });

    cadastrarImagem3.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta3Path = escolherImagem();
            if (imagemResposta3Path != null) {
                mostrarImagemNoLabel(imagemResposta3Path, cadastrarImagem3);
            }
        }
    });

    cadastrarImagem4.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            imagemResposta4Path = escolherImagem();
            if (imagemResposta4Path != null) {
                mostrarImagemNoLabel(imagemResposta4Path, cadastrarImagem4);
            }
        }
    });
}
    
    private String escolherImagem(){
        JFileChooser chooser = new JFileChooser();
       chooser.setDialogTitle("Selecionar imagem");
       
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens (*.jpg, *.jpeg, *.png)","jpg","jpeg", "png");
       chooser.setFileFilter(filtro);
       int resultado = chooser.showOpenDialog(this);
       if(resultado == JFileChooser.APPROVE_OPTION){
           File arquivo = chooser.getSelectedFile();
           return arquivo.getAbsolutePath();
       }
       return null;
    }
    
    private void mostrarImagemNoLabel(String caminho,javax.swing.JLabel label){
        ImageIcon icon = new ImageIcon(caminho);
        Image img = icon.getImage();
        
        Image imgRedimensionada = img.getScaledInstance(
        label.getWidth(),
        label.getHeight(),
        Image.SCALE_SMOOTH);
        label.setText("");
        label.setIcon(new ImageIcon(imgRedimensionada));
    };
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CorretaBox;
    private javax.swing.JLabel DificuldadeLabel;
    private javax.swing.JLabel DificuldadeLabel1;
    private javax.swing.JButton botãoCadastrar;
    private javax.swing.JComboBox<String> botãoDificuldade;
    private javax.swing.JButton botãoFecharTotal;
    private javax.swing.JButton botãoSair;
    private javax.swing.JButton botãoSom;
    private javax.swing.JTextField cadastrarDica;
    private javax.swing.JLabel cadastrarImagem1;
    private javax.swing.JLabel cadastrarImagem2;
    private javax.swing.JLabel cadastrarImagem3;
    private javax.swing.JLabel cadastrarImagem4;
    private javax.swing.JLabel cadastrarImagemPergunta;
    private javax.swing.JTextField cadastrarPergunta;
    private javax.swing.JTextField cadastrarResposta1;
    private javax.swing.JTextField cadastrarResposta2;
    private javax.swing.JTextField cadastrarResposta3;
    private javax.swing.JTextField cadastrarResposta4;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JLabel dica;
    private javax.swing.JLabel identificadorPergunta;
    private javax.swing.JLabel nomePágina;
    private javax.swing.JLabel reposta1;
    private javax.swing.JLabel resposta2;
    private javax.swing.JLabel resposta3;
    private javax.swing.JLabel resposta4;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
