package com.mycompany.pi;

import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author danda
 */
public class TelaDificuldade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDificuldade.class.getName());
    private String nome;
    private int idAluno;
    /**
     * Creates new form TelaDificuldade
     */
    public TelaDificuldade(String nome, int idAluno) {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.nome = nome;
        this.idAluno = idAluno;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();
        medioButton = new javax.swing.JButton();
        shuffleButton = new javax.swing.JButton();
        facilButton = new javax.swing.JButton();
        dificilButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();
        SomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(255, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(220, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        medioButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        medioButton.setText("Médio");
        medioButton.addActionListener(this::medioButtonActionPerformed);

        shuffleButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        shuffleButton.setText("Shuffle");
        shuffleButton.addActionListener(this::shuffleButtonActionPerformed);

        facilButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        facilButton.setText("Fácil");
        facilButton.addActionListener(this::facilButtonActionPerformed);

        dificilButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dificilButton.setText("Difícil");
        dificilButton.addActionListener(this::dificilButtonActionPerformed);

        sairButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sairButton.setText("Sair");
        sairButton.addActionListener(this::sairButtonActionPerformed);

        SomButton.setText("Som");
        SomButton.addActionListener(this::SomButtonActionPerformed);

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 567, Short.MAX_VALUE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                            .addComponent(SomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                            .addComponent(facilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(554, 554, 554))
                        .addGroup(cinzaPaneLayout.createSequentialGroup()
                            .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dificilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(shuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(610, 610, 610)))
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addComponent(vermelhoPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(facilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(medioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(dificilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(shuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medioButtonActionPerformed
        // TODO add your handling code here:
        TelaJogo tela = new TelaJogo("medio",nome,idAluno);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_medioButtonActionPerformed

    private void shuffleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleButtonActionPerformed
        // TODO add your handling code here:
        TelaJogo tela = new TelaJogo("shuffle",nome,idAluno);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shuffleButtonActionPerformed

    private void facilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facilButtonActionPerformed
        // TODO add your handling code here:
        TelaJogo tela = new TelaJogo("facil",nome,idAluno);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_facilButtonActionPerformed

    private void dificilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificilButtonActionPerformed
        // TODO add your handling code here:
        TelaJogo tela = new TelaJogo("dificil",nome,idAluno);
        tela.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_dificilButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        // TODO add your handling code here:
        TelaAluno tela = new TelaAluno(nome,idAluno);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void SomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomButtonActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_SomButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDificuldade("",1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SomButton;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JButton dificilButton;
    private javax.swing.JButton facilButton;
    private javax.swing.JButton medioButton;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton shuffleButton;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
