/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import javax.swing.JFrame;

/**
 *
 * @author danda
 */
public class TelaPréClassificações extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPréClassificações.class.getName());

    /**
     * Creates new form TelaDificuldade
     */
    public TelaPréClassificações() {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        botãoFecharTotal = new javax.swing.JButton();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botãoVoltar = new javax.swing.JButton();
        botãoDesempenho = new javax.swing.JButton();
        botãoRanking = new javax.swing.JButton();
        botãoSom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));
        cinzaPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(225, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        botãoFecharTotal.setText("X");

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botãoFecharTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botãoFecharTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(225, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 769, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        botãoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoVoltar.setText("Voltar");
        botãoVoltar.addActionListener(this::botãoVoltarActionPerformed);

        botãoDesempenho.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botãoDesempenho.setText("Desempenho");
        botãoDesempenho.addActionListener(this::botãoDesempenhoActionPerformed);

        botãoRanking.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botãoRanking.setText("Ranking");
        botãoRanking.addActionListener(this::botãoRankingActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botãoDesempenho, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(botãoRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(botãoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(botãoRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botãoDesempenho, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(botãoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        botãoSom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botãoSom.setText("Som");
        botãoSom.addActionListener(this::botãoSomActionPerformed);

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1108, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cinzaPaneLayout.createSequentialGroup()
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoVoltarActionPerformed
        // TODO add your handling code here:
        TelaProfessor tela = new TelaProfessor();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoVoltarActionPerformed

    private void botãoRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoRankingActionPerformed
        // TODO add your handling code here:
        TelaRanking tela = new TelaRanking();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoRankingActionPerformed

    private void botãoDesempenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoDesempenhoActionPerformed
        // TODO add your handling code here:
        TelaDesempenho tela = new TelaDesempenho();
        tela.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_botãoDesempenhoActionPerformed

    private void botãoSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSomActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_botãoSomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPréClassificações().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãoDesempenho;
    private javax.swing.JButton botãoFecharTotal;
    private javax.swing.JButton botãoRanking;
    private javax.swing.JButton botãoSom;
    private javax.swing.JButton botãoVoltar;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
