/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pi;

import javax.swing.JFrame;

/**
 *
 * @author danda
 */
public class TelaAluno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAluno.class.getName());
    private String nomeAluno;
    private int idAluno;

    /**
     * Creates new form TelaDificuldade
     */
    public TelaAluno(String nomeAluno, int idAluno) {
        setUndecorated(true);
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.nomeAluno = nomeAluno;
        colocarUsuário.setText(nomeAluno);
        colocarUsuário.setEditable(false);
        this.idAluno = idAluno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cinzaPane = new javax.swing.JPanel();
        vermelhoPane1 = new javax.swing.JPanel();
        cinzaEscuroPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nomePágina = new javax.swing.JLabel();
        botãoJogar = new javax.swing.JButton();
        botãoSair = new javax.swing.JButton();
        botãoRanking = new javax.swing.JButton();
        botãoSom = new javax.swing.JButton();
        colocarUsuário = new javax.swing.JTextField();
        nomeUsuário = new javax.swing.JLabel();
        Icone = new javax.swing.JLabel();
        vermelhoPane2 = new javax.swing.JPanel();
        cinzaEscuroPane2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        cinzaPane.setBackground(new java.awt.Color(204, 204, 204));
        cinzaPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        vermelhoPane1.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane1.setPreferredSize(new java.awt.Dimension(255, 333));

        cinzaEscuroPane.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPaneLayout = new javax.swing.GroupLayout(cinzaEscuroPane);
        cinzaEscuroPane.setLayout(cinzaEscuroPaneLayout);
        cinzaEscuroPaneLayout.setHorizontalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        cinzaEscuroPaneLayout.setVerticalGroup(
            cinzaEscuroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane1Layout = new javax.swing.GroupLayout(vermelhoPane1);
        vermelhoPane1.setLayout(vermelhoPane1Layout);
        vermelhoPane1Layout.setHorizontalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane1Layout.setVerticalGroup(
            vermelhoPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomePágina.setFont(new java.awt.Font("Eras Bold ITC", 0, 48)); // NOI18N
        nomePágina.setText("BEM VINDO");

        botãoJogar.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        botãoJogar.setText("Jogar");
        botãoJogar.addActionListener(this::botãoJogarActionPerformed);

        botãoSair.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botãoSair.setText("Sair");
        botãoSair.addActionListener(this::botãoSairActionPerformed);

        botãoRanking.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        botãoRanking.setText("Ranking");
        botãoRanking.addActionListener(this::botãoRankingActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botãoJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botãoRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botãoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nomePágina)
                        .addGap(250, 250, 250))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(nomePágina, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botãoJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(botãoRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(botãoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        botãoSom.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botãoSom.setText("Som");
        botãoSom.addActionListener(this::botãoSomActionPerformed);

        colocarUsuário.addActionListener(this::colocarUsuárioActionPerformed);

        nomeUsuário.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nomeUsuário.setText("Usuário:");

        Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/R (1).png"))); // NOI18N
        Icone.setText("Icone");

        javax.swing.GroupLayout cinzaPaneLayout = new javax.swing.GroupLayout(cinzaPane);
        cinzaPane.setLayout(cinzaPaneLayout);
        cinzaPaneLayout.setHorizontalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addContainerGap(325, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(341, 341, 341))
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Icone, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeUsuário))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cinzaPaneLayout.createSequentialGroup()
                                .addComponent(colocarUsuário, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vermelhoPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        cinzaPaneLayout.setVerticalGroup(
            cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cinzaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cinzaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botãoSom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cinzaPaneLayout.createSequentialGroup()
                        .addComponent(Icone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeUsuário)))
                .addGap(9, 9, 9)
                .addComponent(colocarUsuário, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addComponent(vermelhoPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
        );

        vermelhoPane2.setBackground(new java.awt.Color(148, 22, 17));
        vermelhoPane2.setPreferredSize(new java.awt.Dimension(220, 333));

        cinzaEscuroPane2.setBackground(new java.awt.Color(74, 85, 92));

        javax.swing.GroupLayout cinzaEscuroPane2Layout = new javax.swing.GroupLayout(cinzaEscuroPane2);
        cinzaEscuroPane2.setLayout(cinzaEscuroPane2Layout);
        cinzaEscuroPane2Layout.setHorizontalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );
        cinzaEscuroPane2Layout.setVerticalGroup(
            cinzaEscuroPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vermelhoPane2Layout = new javax.swing.GroupLayout(vermelhoPane2);
        vermelhoPane2.setLayout(vermelhoPane2Layout);
        vermelhoPane2Layout.setHorizontalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vermelhoPane2Layout.setVerticalGroup(
            vermelhoPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vermelhoPane2Layout.createSequentialGroup()
                .addGap(0, 756, Short.MAX_VALUE)
                .addComponent(cinzaEscuroPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vermelhoPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinzaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colocarUsuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colocarUsuárioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colocarUsuárioActionPerformed

    private void botãoSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSomActionPerformed
        // TODO add your handling code here:
        TelaSom telaSom = new TelaSom(this);
        telaSom.setVisible(true);
    }//GEN-LAST:event_botãoSomActionPerformed

    private void botãoJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoJogarActionPerformed
        // TODO add your handling code here:
        TelaDificuldade tela = new TelaDificuldade(nomeAluno,idAluno);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoJogarActionPerformed

    private void botãoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoSairActionPerformed
        // TODO add your handling code here:
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoSairActionPerformed

    private void botãoRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoRankingActionPerformed
        // TODO add your handling code here:
        TelaRankingAluno tela = new TelaRankingAluno(nomeAluno,idAluno);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botãoRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAluno("",1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icone;
    private javax.swing.JButton botãoJogar;
    private javax.swing.JButton botãoRanking;
    private javax.swing.JButton botãoSair;
    private javax.swing.JButton botãoSom;
    private javax.swing.JPanel cinzaEscuroPane;
    private javax.swing.JPanel cinzaEscuroPane2;
    private javax.swing.JPanel cinzaPane;
    private javax.swing.JTextField colocarUsuário;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomePágina;
    private javax.swing.JLabel nomeUsuário;
    private javax.swing.JPanel vermelhoPane1;
    private javax.swing.JPanel vermelhoPane2;
    // End of variables declaration//GEN-END:variables
}
